version: '3.8'
services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/yourDatabase
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
